#!/usr/bin/env sh

# Layout System
yabai -m config layout                        bsp
yabai -m config mouse_follows_focus           on
yabai -m config focus_follows_mouse           autoraise
yabai -m config window_topmost                on
yabai -m config window_opacity                off
yabai -m config window_shadow                 on
yabai -m config window_border                 on
yabai -m config active_window_border_color    0xffFF55AB
yabai -m config normal_window_border_color    0xff505050
yabai -m config auto_balance                  off
yabai -m config active_window_opacity         1.0
yabai -m config normal_window_opacity         0.90


# Variables
CENTERED_GRID=4:4:1:1:2:2


# Window Padding
yabai -m config top_padding    30
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10


# Applications
yabai -m rule --add app="^System Preferences$" manage=off grid=$CENTERED_GRID
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on grid=5:5:4:4:1:1
yabai -m rule --add app="^Firefox$" title="^Opening .*$" manage=off  
yabai -m rule --add app=Preview manage=off border=off
yabai -m rule --add app=Finder manage=off topmost=off
yabai -m rule --add app=Android\ Studio manage=off topmost=off


# Delete Empty Spaces
read -r -d '' destroy_space <<- 'EOF'
  recent_space_index="$(yabai -m query --spaces | 
    jq -er 'map(select(.id | tostring == env.YABAI_RECENT_SPACE_ID))[0].index')"
  if yabai -m query --windows --space "${recent_space_index}" |
    jq -er 'length == 0'
  then
    yabai -m space "${recent_space_index}" --destroy
  fi
EOF

yabai -m signal --add event="space_changed" action="${destroy_space}"
yabai -m signal --add event="application_terminated" action="${destroy_space}"


